### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by tony1747** [kylessmith/cfdna#1]
I have the following error messages from running the command "pip install -r requirements.txt'.

D:\cfdna-main\cfdna-main>pip install -r requirements.txt
WARNING: Ignoring invalid distribution -ip (d:\python\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\python\lib\site-packages)
Requirement already satisfied: numpy>=1.0.0 in d:\python\lib\site-packages (from -r requirements.txt (line 1)) (1.18.2)
Requirement already satisfied: pandas>=1.0.0 in d:\python\lib\site-packages (from -r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: cython>=0.29.0 in d:\python\lib\site-packages (from -r requirements.txt (line 3)) (0.29.26)
Requirement already satisfied: pytest>=5.4.0 in d:\python\lib\site-packages (from -r requirements.txt (line 4)) (6.2.5)
Collecting ngsfragments>=1.0.0
  Using cached ngsfragments-1.0.8.tar.gz (52.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lirun\AppData\Local\Temp\pip-install-esbxa8kc\ngsfragments_0fc79bbdf9774a2fa1d3f0f75ac8b16c\setup.py", line 3, in <module>
          import ailist
      ModuleNotFoundError: No module named 'ailist'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: Ignoring invalid distribution -ip (d:\python\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\python\lib\site-packages)

**Comment by tony1747** [comment]
Can anybody explain what is going wrong here?

**Comment by kylessmith** [comment]
It looks to me that you might not have ailist installed. Try "pip install ailist". After that it is possible you will need to pip install cbseg, bcpseg, hmmcopy, intervalframe, and ngsfragments. It seems that sometimes pip won't find these packages on its own. I am currently working to find out why.
